# Maximalist Dashboard for Home Assistant
# For use on Astralplane
# Made by Madelena Mak 2022
# https://mmak.es

title: Dashboard

views:
  - !include views/summary.yaml
  - !include views/network.yaml
  - !include views/energy.yaml
  - !include views/lights.yaml
  - !include views/security.yaml
  - !include views/maintenance.yaml
  - !include views/environment.yaml
  - !include views/neighborhood.yaml
  - !include views/media.yaml
  - !include views/me.yaml
  - !include views/astrometrics.yaml

decluttering_templates: !include templates/decluttering-card.yaml
button_card_templates: !include_dir_merge_named templates/button-card/
apexcharts_card_templates: !include templates/apexcharts-card.yaml
popup_cards: !include_dir_merge_named popups/

swipe_nav:
  animate: swipe
  prevent_default: true

kiosk_mode:
  user_settings:
    - users:
        - Strawberry
        - Maddy
      hide_sidebar: true
      hide_menubutton: true
      hide_overflow: true
  mobile_settings:
    hide_menubutton: true
    hide_overflow: true

# Remove the x for background.
xbackground: >-
  linear-gradient(to bottom, rgba(var(--rgb-primary-color),.2),
  var(--primary-background-color))
