# Madelena + The Machines
# Made by Madelena Mak 2022
# https://mmak.es

title: My Machines
# Yes, it's the one by Battles ft. Gary Numan

views:
  - !include views/machines/all-devices.yaml
  - !include views/machines/unison.yaml
  - !include views/machines/terpsichora.yaml
  - !include views/machines/genesis.yaml
  - !include views/machines/dorothy.yaml
  - !include views/machines/illinoise.yaml
  - !include views/machines/astralplane.yaml
  - !include views/machines/printers.yaml
# Car, and maybe Fridge, Microwave

decluttering_templates: !include templates/decluttering-card.yaml
button_card_templates: !include_dir_merge_named templates/button-card/

swipe_nav:
  animate: swipe
  prevent_default: true
