# Rooms Dashboard
# Made by Madelena Mak 2022
# https://mmak.es

title: Rooms

views:
  # - !include views/rooms/summary.yaml
  - !include views/rooms/living-room.yaml
  - !include views/rooms/kitchen.yaml
  - !include views/rooms/workspace.yaml
  - !include views/rooms/bedroom.yaml
  # - !include views/rooms/bathroom.yaml

decluttering_templates: !include templates/decluttering-card.yaml
button_card_templates: !include_dir_merge_named templates/button-card/

swipe_nav:
  animate: swipe
  prevent_default: true
