# The Ambient Smart Displays Dashboard
# For use on tablets, Echo Show, and Google Home displays
# Made by Madelena Mak 2022
# https://mmak.es


title: Smart Display (Bedroom)

decluttering_templates: !include templates/decluttering-card.yaml
button_card_templates: !include_dir_merge_named templates/button-card/

views:
  - !include smartdisplays/views/home-bedroom.yaml
  - !include smartdisplays/views/home-bedroom-clock-only.yaml
  - !include smartdisplays/views/start.yaml
  - !include smartdisplays/views/chores.yaml
  - !include smartdisplays/views/lights.yaml
  - !include smartdisplays/views/climate.yaml
  - !include smartdisplays/views/vacuum.yaml
  - !include smartdisplays/views/music.yaml
  - !include smartdisplays/views/tv.yaml
  - !include smartdisplays/views/energy.yaml
  - !include smartdisplays/views/weather.yaml


